### ISSUE TITLE
Dockerfiles depend on external git repo

### ISSUE THREAD

**Issue by juanmb** [jochym/indi#2]
First of all, thanks for the great work with CircleCI and the docker containers!

I know a Dockerfile cannot access files outside its containing directory, but downloading the `run-build.sh` script from an external github repository is not a good solution. It makes this script impossible to modify for everyone. I think it is preferable to have a copy of this script in every folder.

Maybe the `build-dockers` script could copy the original `run-build.sh` into every folder before building the docker image.

**Comment by jochym** [comment]
You are right regarding the modifiability of the script. This is not the final solution. Some of the infrastructure is on my personal account on dockerhub. This must and will be migrated to the proper indilib account and all data (scripts) will end up in the upstream repositories. Right now some of it is in  my _public_ repos and I will be only too happy to accept any interesting PR against these repos. As you are surely aware, the build machine is a bit fragile right now (too much of rube-goldberg machine in it) so I prefer to keep a closer eye on it for some time yet. The problem with your solution is that the build is executed on dockerhub and cannot use anything outside of the dockerfile directory - so using the repo directly is the only solution I know. The next step will be switching to the upstream repo for run-build.sh script. Note also that this script is _not_ used in the build process. This is only auxiliary tool for driver developers - see README.md in docker directory for the explanation.

**Comment by jochym** [comment]
Closing - the CI is based on Actions now
