### ISSUE TITLE
Unit tests not running

### ISSUE THREAD

**Issue by juanmb** [jochym/indi#3]
Unit tests are not being run because gtest and gmock libraries are not installed in the containers.
"apt install googletest" installs the source code of both libraries, but it's necessary to build and install the libraries by calling "make".

I made a PR to the main indi repository fixing this issue for debian/ubuntu based containers: https://github.com/indilib/indi/pull/485 . Something similar has to be done in the other Dockerfiles, but the installation process will be different in other distributions.

Could you please update the docker images?

**Comment by jochym** [comment]
I will. Thanks for the heads-up.

niedz., 31.12.2017, 14:16 użytkownik Juan Menéndez <notifications@github.com>
napisał:

**Comment by jochym** [comment]
Dockers already updated and config also modified accordingly in https://github.com/indilib/indi/pull/488
The updated images are already on dockerhub.

**Comment by juanmb** [comment]
Thank you! great work!
